'use strict';
const fs = require('fs');
const path = require('path');

const cur = JSON.parse(fs.readFileSync(path.join(__dirname, '../src/data/curriculum.json'), 'utf8'));

// ─── CHAPTER 2 ─────────────────────────────────────────────────────────────
const ch02 = {
  id: 'ch-02',
  title: 'Part 2: Java Tools & Techniques',
  description: 'Random numbers, the Math class, formatted output with printf, nested conditions, and String methods.',
  lessons: [
    // ── L2-1: Random Class ──────────────────────────────────────────────────
    {
      id: 'le-02-01',
      title: 'The Random Class',
      slides: [
        {
          id: 'sl-02-01-01', timestamp: '1:22:25',
          title: 'Importing and Creating a Random Object',
          content: 'The Random class generates pseudo-random numbers — import and instantiate it like Scanner.',
          bullets: [
            'Add import java.util.Random; at the top of your file, before the class declaration',
            'Create one Random object: Random random = new Random();',
            'The Random class follows the same import-instantiate-use pattern as Scanner',
            'Random numbers are pseudo-random — generated by a deterministic algorithm seeded from the clock'
          ],
          code: 'import java.util.Random;\n\npublic class Main {\n    public static void main(String[] args) {\n\n        Random random = new Random();\n\n        // Call methods on \'random\' to generate values\n        int number = random.nextInt(10); // 0 to 9\n        System.out.println(\"Random number: \" + number);\n    }\n}',
          instructorNotes: 'Video: 1:22:25'
        },
        {
          id: 'sl-02-01-02', timestamp: '1:23:10',
          title: 'nextInt() — Integers in a Range',
          content: 'nextInt(bound) generates an integer from 0 inclusive to bound exclusive.',
          bullets: [
            'random.nextInt(bound) returns 0 to bound-1 — the bound itself is never returned',
            'Simulating a 6-sided die (1-6): random.nextInt(6) + 1',
            'The + 1 shifts the range: without it you get 0-5, with it you get 1-6',
            'General range min to max: random.nextInt(max - min + 1) + min'
          ],
          code: 'import java.util.Random;\n\npublic class Main {\n    public static void main(String[] args) {\n        Random random = new Random();\n\n        // 0 to 9\n        int num = random.nextInt(10);\n        System.out.println(\"0-9: \" + num);\n\n        // 6-sided die — shift by +1 for 1-6\n        int die = random.nextInt(6) + 1;\n        System.out.println(\"Die: \" + die);\n\n        // Custom range 50 to 100\n        int score = random.nextInt(51) + 50;\n        System.out.println(\"Score: \" + score);\n    }\n}',
          instructorNotes: 'Video: 1:23:10'
        },
        {
          id: 'sl-02-01-03', timestamp: '1:24:30',
          title: 'nextDouble() and nextBoolean()',
          content: 'nextDouble() produces a decimal from 0.0 to just below 1.0; nextBoolean() gives random true or false.',
          bullets: [
            'random.nextDouble() returns a double from 0.0 (inclusive) to 1.0 (exclusive)',
            'Scale to a range: random.nextDouble() * 100.0 gives 0.0 to 99.9...',
            'random.nextBoolean() returns true or false with equal 50% probability',
            'Use nextBoolean() to simulate coin flips, random yes/no decisions, or toggle flags'
          ],
          code: 'import java.util.Random;\n\npublic class Main {\n    public static void main(String[] args) {\n        Random random = new Random();\n\n        // 0.0 to just below 1.0\n        double d = random.nextDouble();\n        System.out.println(\"Double: \" + d);\n\n        // Scale to 0.0 to 100.0\n        double pct = random.nextDouble() * 100.0;\n        System.out.printf(\"Percent: %.2f%n\", pct);\n\n        // Coin flip\n        boolean heads = random.nextBoolean();\n        System.out.println(heads ? \"Heads\" : \"Tails\");\n    }\n}',
          instructorNotes: 'Video: 1:24:30'
        },
        {
          id: 'sl-02-01-04', timestamp: '1:25:40',
          title: 'Practice: Dice Roller',
          content: 'Roll two dice, sum them, and announce whether the total is a winning 7.',
          bullets: [
            'Roll each die separately: random.nextInt(6) + 1 gives values 1-6',
            'Sum the two results — two dice produce totals from 2 to 12',
            'Print both individual rolls and the combined total',
            'A total of 7 wins — use an if statement to announce the result'
          ],
          code: 'import java.util.Random;\n\npublic class Main {\n    public static void main(String[] args) {\n        Random random = new Random();\n\n        int die1  = random.nextInt(6) + 1;\n        int die2  = random.nextInt(6) + 1;\n        int total = die1 + die2;\n\n        System.out.println(\"Die 1: \" + die1);\n        System.out.println(\"Die 2: \" + die2);\n        System.out.println(\"Total: \" + total);\n\n        if (total == 7) {\n            System.out.println(\"You win!\");\n        } else {\n            System.out.println(\"Try again.\");\n        }\n    }\n}',
          instructorNotes: 'Video: 1:25:40'
        }
      ]
    },
    // ── L2-2: Math Class ────────────────────────────────────────────────────
    {
      id: 'le-02-02',
      title: 'The Math Class',
      slides: [
        {
          id: 'sl-02-02-01', timestamp: '1:27:30',
          title: 'Math Constants — PI and E',
          content: 'The Math class provides built-in constants and methods — no import required.',
          bullets: [
            'Math is in java.lang — auto-imported, no import statement needed',
            'Math.PI holds pi (3.14159...) as a double constant',
            'Math.E holds Euler\'s number (2.71828...) used in natural logarithms',
            'Always prefix with Math. and use UPPERCASE: Math.PI, Math.E'
          ],
          code: 'public class Main {\n    public static void main(String[] args) {\n\n        System.out.println(Math.PI);  // 3.141592653589793\n        System.out.println(Math.E);   // 2.718281828459045\n\n        // Area of a circle: A = PI * r^2\n        double radius = 5.0;\n        double area   = Math.PI * radius * radius;\n        System.out.printf(\"Area: %.4f%n\", area);  // 78.5398\n    }\n}',
          instructorNotes: 'Video: 1:27:30'
        },
        {
          id: 'sl-02-02-02', timestamp: '1:29:00',
          title: 'Rounding — round(), ceil(), floor()',
          content: 'Java provides three distinct rounding behaviours through the Math class.',
          bullets: [
            'Math.round(x) rounds to the nearest whole number — .5 rounds up — returns a long',
            'Math.ceil(x) always rounds UP to the next whole number — returns a double',
            'Math.floor(x) always rounds DOWN to the previous whole number — returns a double',
            'For negatives: ceil(-2.9) = -2.0, floor(-2.9) = -3.0 — ceiling is closer to zero'
          ],
          code: 'double x = 3.6, y = 3.4;\n\nSystem.out.println(Math.round(x));  // 4   — nearest\nSystem.out.println(Math.round(y));  // 3   — nearest\nSystem.out.println(Math.ceil(y));   // 4.0 — always up\nSystem.out.println(Math.floor(x));  // 3.0 — always down\n\n// Negative values:\nSystem.out.println(Math.ceil(-2.9));   // -2.0 — up toward zero\nSystem.out.println(Math.floor(-2.9));  // -3.0 — down away from zero',
          instructorNotes: 'Video: 1:29:00'
        },
        {
          id: 'sl-02-02-03', timestamp: '1:31:00',
          title: 'pow(), sqrt(), abs(), max(), min()',
          content: 'The five most-used Math methods in everyday Java programming.',
          bullets: [
            'Math.pow(base, exp) raises base to the power of exp — returns a double',
            'Math.sqrt(x) returns the square root of x as a double',
            'Math.abs(x) returns the absolute value — strips the negative sign',
            'Math.max(a, b) and Math.min(a, b) return the larger or smaller of two values'
          ],
          code: 'System.out.println(Math.pow(2, 10));    // 1024.0  (2^10)\nSystem.out.println(Math.pow(9, 0.5));   // 3.0     (square root via pow)\nSystem.out.println(Math.sqrt(144));     // 12.0\nSystem.out.println(Math.abs(-47));      // 47\nSystem.out.println(Math.abs(-3.14));    // 3.14\n\nSystem.out.println(Math.max(18, 25));   // 25\nSystem.out.println(Math.min(18, 25));   // 18',
          instructorNotes: 'Video: 1:31:00'
        },
        {
          id: 'sl-02-02-04', timestamp: '1:33:00',
          title: 'Practice: Hypotenuse Calculator',
          content: 'Apply Math.pow() and Math.sqrt() to compute the hypotenuse of a right triangle.',
          bullets: [
            'Pythagorean theorem: c = sqrt(a^2 + b^2)',
            'Math.pow(a, 2) squares side a — add both, then take Math.sqrt()',
            'Accept a and b from the user with Scanner',
            'printf with %.2f rounds the result to two decimal places'
          ],
          code: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n\n        System.out.print(\"Enter side a: \"); double a = sc.nextDouble();\n        System.out.print(\"Enter side b: \"); double b = sc.nextDouble();\n        sc.close();\n\n        double c = Math.sqrt(Math.pow(a, 2) + Math.pow(b, 2));\n        System.out.printf(\"Hypotenuse c = %.2f%n\", c);\n    }\n}',
          instructorNotes: 'Video: 1:33:00'
        }
      ]
    },
    // ── L2-3: printf ────────────────────────────────────────────────────────
    {
      id: 'le-02-03',
      title: 'printf — Formatted Output',
      slides: [
        {
          id: 'sl-02-03-01', timestamp: '1:42:44',
          title: 'Why printf?',
          content: 'System.out.printf() formats output precisely — controlling decimal places, field widths, and variable placement.',
          bullets: [
            'printf = print formatted — inserts variables into a template string via % placeholders',
            'Placeholders: %s (String), %d (int), %f (double), %c (char), %b (boolean)',
            'printf does NOT add a newline — use %n (or \\n) at the end of the format string',
            'Prefer printf over concatenation when you need precise alignment or decimal control'
          ],
          code: 'String name = \"Alex\";\nint    age  = 21;\n\n// Concatenation\nSystem.out.println(\"Name: \" + name + \", Age: \" + age);\n\n// printf — cleaner, more precise\nSystem.out.printf(\"Name: %s, Age: %d%n\", name, age);\n// Name: Alex, Age: 21\n\n// Multiple variables listed in order after the format string\nSystem.out.printf(\"%s is %d years old.%n\", name, age);\n// Alex is 21 years old.',
          instructorNotes: 'Video: 1:42:44'
        },
        {
          id: 'sl-02-03-02', timestamp: '1:44:30',
          title: 'Format Specifiers — %s, %d, %c, %b',
          content: 'Each data type has a corresponding format specifier character in printf.',
          bullets: [
            '%s — String (any object converted to text)',
            '%d — integer (int or long) — stands for decimal integer',
            '%c — char — displays a single character',
            '%b — boolean — displays true or false'
          ],
          code: 'String  name   = \"Alice\";\nint     score  = 95;\nchar    grade  = \'A\';\nboolean passed = true;\n\nSystem.out.printf(\"Student: %s%n\",  name);    // Student: Alice\nSystem.out.printf(\"Score:   %d%n\",  score);   // Score:   95\nSystem.out.printf(\"Grade:   %c%n\",  grade);   // Grade:   A\nSystem.out.printf(\"Passed:  %b%n\",  passed);  // Passed:  true\n\n// All in one line:\nSystem.out.printf(\"%s scored %d (%c). Passed: %b%n\", name, score, grade, passed);',
          instructorNotes: 'Video: 1:44:30'
        },
        {
          id: 'sl-02-03-03', timestamp: '1:47:00',
          title: 'Double Precision — %f and %.2f',
          content: 'Use %f for doubles — control decimal places with a dot-precision modifier.',
          bullets: [
            '%f displays a double with 6 decimal places by default',
            '%.2f limits the output to exactly 2 decimal places — standard for prices',
            '%.0f rounds to the nearest whole number with no decimal point shown',
            'Modifier syntax: %.Nf where N is the number of decimal places'
          ],
          code: 'double price = 9.99;\ndouble pi    = Math.PI;\n\nSystem.out.printf(\"%f%n\",    price);  // 9.990000  (6 decimal default)\nSystem.out.printf(\"%.2f%n\", price);  // 9.99\nSystem.out.printf(\"%.0f%n\", pi);     // 3\nSystem.out.printf(\"%.4f%n\", pi);     // 3.1416\n\n// Currency\nSystem.out.printf(\"Total: $%.2f%n\", 1234.5678);  // Total: $1234.57',
          instructorNotes: 'Video: 1:47:00'
        },
        {
          id: 'sl-02-03-04', timestamp: '1:51:00',
          title: 'Width and Alignment',
          content: 'A width number reserves a minimum field size — use - for left-alignment.',
          bullets: [
            '%10d reserves 10 characters and right-aligns the integer',
            '%-10s reserves 10 characters and left-aligns the String (minus = left)',
            'Width is the minimum field — content wider than width is not truncated',
            'Combine width and precision: %10.2f = 10 chars wide, 2 decimal places'
          ],
          code: 'System.out.printf(\"%-15s %6s%n\", \"Item\",          \"Price\");\nSystem.out.printf(\"%-15s %6s%n\", \"----\",          \"-----\");\nSystem.out.printf(\"%-15s $%5.2f%n\", \"Java Book\",    29.99);\nSystem.out.printf(\"%-15s $%5.2f%n\", \"USB Cable\",     9.49);\nSystem.out.printf(\"%-15s $%5.2f%n\", \"Keyboard\",     74.99);\n// Output:\n// Item             Price\n// ----             -----\n// Java Book       $29.99\n// USB Cable        $9.49\n// Keyboard        $74.99',
          instructorNotes: 'Video: 1:51:00'
        },
        {
          id: 'sl-02-03-05', timestamp: '1:54:00',
          title: 'Practice: Formatted Receipt',
          content: 'Use printf to print a shopping receipt with aligned item names and right-justified prices.',
          bullets: [
            'Left-align item names with %-20s, right-align prices with $%6.2f',
            'Use a separator line of dashes for visual structure',
            'Compute the total and display it with the same alignment',
            'This table pattern appears in real-world billing, banking, and report code'
          ],
          code: 'double book = 29.99, cable = 9.49, kb = 74.99;\ndouble total = book + cable + kb;\n\nSystem.out.printf(\"%-20s %7s%n\", \"Item\",         \"Price\");\nSystem.out.printf(\"%-20s %7s%n\", \"----\",         \"-----\");\nSystem.out.printf(\"%-20s $%6.2f%n\", \"Java Book\",  book);\nSystem.out.printf(\"%-20s $%6.2f%n\", \"USB Cable\",  cable);\nSystem.out.printf(\"%-20s $%6.2f%n\", \"Keyboard\",   kb);\nSystem.out.printf(\"%-20s %7s%n\", \"----\",         \"-----\");\nSystem.out.printf(\"%-20s $%6.2f%n\", \"Total\",      total);',
          instructorNotes: 'Video: 1:54:00'
        }
      ]
    },
    // ── L2-4: Compound Interest ─────────────────────────────────────────────
    {
      id: 'le-02-04',
      title: 'Compound Interest Calculator',
      slides: [
        {
          id: 'sl-02-04-01', timestamp: '1:56:17',
          title: 'Project: Compound Interest',
          content: 'Apply Math.pow() and printf to a real-world finance formula.',
          bullets: [
            'Compound interest grows on both the principal and previously earned interest',
            'Formula: A = P * (1 + r/n)^(n*t)',
            'P = principal, r = annual rate as decimal, n = compoundings per year, t = years',
            'A is the final amount — A minus P gives the total interest earned'
          ],
          code: '// A = P * (1 + r/n)^(n*t)\n//\n// P = 1000.00  starting amount\n// r = 0.05     5% annual rate (as a decimal)\n// n = 12       compounded monthly\n// t = 10       years\n\ndouble P = 1000.00;\ndouble r = 0.05;\nint    n = 12;\nint    t = 10;\n\n// Compute on next slide',
          instructorNotes: 'Video: 1:56:17'
        },
        {
          id: 'sl-02-04-02', timestamp: '1:58:00',
          title: 'Applying Math.pow()',
          content: 'Math.pow() handles the exponentiation — watch integer division in the base.',
          bullets: [
            'Math.pow(1 + r/n, n*t) computes the growth factor',
            'r is a double, n is an int — r/n is double/int which gives a double result (safe)',
            'Multiply the result by P to get the final amount A',
            'printf with %.2f displays the dollar amounts cleanly'
          ],
          code: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n\n        System.out.print(\"Principal ($): \");          double P = sc.nextDouble();\n        System.out.print(\"Annual rate (e.g. 0.05): \"); double r = sc.nextDouble();\n        System.out.print(\"Times/year compounded: \");  int    n = sc.nextInt();\n        System.out.print(\"Years: \");                  int    t = sc.nextInt();\n        sc.close();\n\n        double A = P * Math.pow(1 + r / n, n * t);\n        System.out.printf(\"Final amount:    $%.2f%n\", A);\n        System.out.printf(\"Interest earned: $%.2f%n\", A - P);\n    }\n}',
          instructorNotes: 'Video: 1:58:00'
        },
        {
          id: 'sl-02-04-03', timestamp: '2:01:00',
          title: 'Compound Interest — Challenge',
          content: 'Compare monthly vs annual compounding side by side to see the difference.',
          bullets: [
            'Run the formula twice: once with n=12 (monthly), once with n=1 (annual)',
            'Display both final amounts and the difference between them',
            'The gap shows why banks advertise compounding frequency — it matters',
            'Challenge: compute how many years to double the money: t = ln(2) / (n * ln(1 + r/n))'
          ],
          code: 'double P = 5000.0;\ndouble r = 0.07;  // 7% annual\nint    t = 20;    // 20 years\n\ndouble monthly = P * Math.pow(1 + r / 12, 12 * t);\ndouble annual  = P * Math.pow(1 + r,       1  * t);\n\nSystem.out.printf(\"Monthly compounding: $%.2f%n\", monthly);\nSystem.out.printf(\"Annual  compounding: $%.2f%n\", annual);\nSystem.out.printf(\"Difference:          $%.2f%n\", monthly - annual);',
          instructorNotes: 'Video: 2:01:00'
        }
      ]
    },
    // ── L2-5: Nested if ─────────────────────────────────────────────────────
    {
      id: 'le-02-05',
      title: 'Nested if Statements',
      slides: [
        {
          id: 'sl-02-05-01', timestamp: '2:03:46',
          title: 'if Inside an if',
          content: 'A nested if checks a secondary condition only after the primary condition is already true.',
          bullets: [
            'A nested if is placed inside the body of another if — it acts as a second gate',
            'The inner if runs only when the outer if condition is true',
            'Each nesting level adds one indentation level — limit to 2-3 levels for readability',
            'Use nesting when condition B only makes sense if condition A is already satisfied'
          ],
          code: 'int age       = 20;\nboolean hasID = true;\n\nif (age >= 18) {\n    // Outer gate passed — check ID\n    if (hasID) {\n        System.out.println(\"Entry granted.\");\n    } else {\n        System.out.println(\"You need photo ID.\");\n    }\n} else {\n    System.out.println(\"Must be 18 or older.\");\n}\n// Output: Entry granted.',
          instructorNotes: 'Video: 2:03:46'
        },
        {
          id: 'sl-02-05-02', timestamp: '2:06:00',
          title: 'Nesting vs else-if — When to Choose',
          content: 'Choose else-if for independent alternatives; choose nesting when condition B depends on condition A.',
          bullets: [
            'Use else-if when conditions are independent alternatives — only one branch runs',
            'Use nesting when condition B is meaningless unless condition A is already true',
            'Deeply nested code is hard to read — flatten with && when possible',
            'if (a && b) { } is usually cleaner than if (a) { if (b) { } } for simple cases'
          ],
          code: '// Nested — B depends on A being true\nif (isLoggedIn) {\n    if (isAdmin) {\n        System.out.println(\"Admin dashboard\");\n    } else {\n        System.out.println(\"User dashboard\");\n    }\n}\n\n// Flattened with && — same result, more readable\nif (isLoggedIn && isAdmin) {\n    System.out.println(\"Admin dashboard\");\n} else if (isLoggedIn) {\n    System.out.println(\"User dashboard\");\n}',
          instructorNotes: 'Video: 2:06:00'
        },
        {
          id: 'sl-02-05-03', timestamp: '2:09:00',
          title: 'Practice: Grade Classifier',
          content: 'Use nested conditions to validate input then classify a score into a letter grade.',
          bullets: [
            'Outer condition: validate the score is in range (0-100)',
            'Inner else-if chain: A >= 90, B >= 80, C >= 70, D >= 60, F otherwise',
            'A second nested if can flag a distinction for scores >= 90',
            'Validate first, classify second — this two-gate pattern mirrors real eligibility logic'
          ],
          code: 'int score = 88;\n\nif (score >= 0 && score <= 100) {\n    String grade;\n    if      (score >= 90) grade = \"A\";\n    else if (score >= 80) grade = \"B\";\n    else if (score >= 70) grade = \"C\";\n    else if (score >= 60) grade = \"D\";\n    else                  grade = \"F\";\n\n    System.out.println(\"Grade: \" + grade);\n\n    if (score >= 90) {\n        System.out.println(\"With Distinction!\");\n    }\n} else {\n    System.out.println(\"Invalid score.\");\n}',
          instructorNotes: 'Video: 2:09:00'
        }
      ]
    },
    // ── L2-6: String Methods ────────────────────────────────────────────────
    {
      id: 'le-02-06',
      title: 'String Methods',
      slides: [
        {
          id: 'sl-02-06-01', timestamp: '2:13:00',
          title: 'Case and Length',
          content: 'String methods are called with a dot after the variable — they return new Strings, leaving the original unchanged.',
          bullets: [
            'str.toUpperCase() returns a new String with all letters capitalised',
            'str.toLowerCase() returns a new String with all letters lowercased',
            'str.length() returns the number of characters as an int — spaces and punctuation count',
            'String methods never modify the original — reassign the variable to keep the change'
          ],
          code: 'String name = \"Alice Smith\";\n\nSystem.out.println(name.toUpperCase());  // ALICE SMITH\nSystem.out.println(name.toLowerCase());  // alice smith\nSystem.out.println(name.length());       // 11\n\n// Reassign to apply the change permanently\nname = name.toUpperCase();\nSystem.out.println(name);  // ALICE SMITH\n\nSystem.out.println(\"\".length());  // 0',
          instructorNotes: 'Video: 2:13:00'
        },
        {
          id: 'sl-02-06-02', timestamp: '2:14:30',
          title: 'charAt() and indexOf()',
          content: 'charAt() reads one character by position; indexOf() finds the first position of a character or substring.',
          bullets: [
            'str.charAt(index) returns the char at the given zero-based index',
            'Strings are zero-indexed: \"Hello\".charAt(0) = \'H\', charAt(4) = \'o\'',
            'str.indexOf(\'x\') returns the first index of character x, or -1 if not found',
            'str.indexOf(\"sub\") finds the starting index of the first occurrence of a substring'
          ],
          code: 'String word  = \"Hello\";\nString email = \"user@example.com\";\n\nSystem.out.println(word.charAt(0));       // H\nSystem.out.println(word.charAt(4));       // o\n\nSystem.out.println(email.indexOf(\'@\'));   // 4\nSystem.out.println(email.indexOf(\"ex\"));  // 5\nSystem.out.println(email.indexOf(\'z\'));   // -1 (not found)',
          instructorNotes: 'Video: 2:14:30'
        },
        {
          id: 'sl-02-06-03', timestamp: '2:16:00',
          title: 'contains(), isEmpty(), replace(), trim()',
          content: 'Four essential methods for searching, checking, and cleaning String values.',
          bullets: [
            'str.contains(\"x\") returns true if the string contains the substring x anywhere',
            'str.isEmpty() returns true if the string has zero characters — same as length() == 0',
            'str.replace(\"old\", \"new\") returns a new String with every occurrence swapped',
            'str.trim() removes leading and trailing whitespace — essential for cleaning user input'
          ],
          code: 'String pwd = \"secure123\";\n\nSystem.out.println(pwd.contains(\"123\"));  // true\nSystem.out.println(pwd.contains(\"xyz\"));  // false\nSystem.out.println(\"\".isEmpty());         // true\nSystem.out.println(pwd.isEmpty());        // false\n\nString s = \"I like cats and cats.\".replace(\"cats\", \"dogs\");\nSystem.out.println(s);  // I like dogs and dogs.\n\nSystem.out.println(\"   hello   \".trim());  // hello',
          instructorNotes: 'Video: 2:16:00'
        },
        {
          id: 'sl-02-06-04', timestamp: '2:17:30',
          title: 'equals() and equalsIgnoreCase()',
          content: 'Never use == to compare String content — always use .equals() or .equalsIgnoreCase().',
          bullets: [
            'str.equals(other) returns true when both strings have identical characters',
            '== on Strings compares memory addresses, not content — it is unreliable for comparison',
            'str.equalsIgnoreCase(other) compares content ignoring uppercase/lowercase differences',
            'Use equalsIgnoreCase() for user input — users may type YES, yes, or Yes'
          ],
          code: 'String a = \"Hello\";\nString b = \"hello\";\n\nSystem.out.println(a.equals(b));            // false — case matters\nSystem.out.println(a.equalsIgnoreCase(b));  // true  — ignores case\n\n// Accept any capitalisation from the user\nString input = \"YES\";\nif (input.equalsIgnoreCase(\"yes\")) {\n    System.out.println(\"Confirmed.\");\n}\n\n// NEVER: if (a == b) -- compares references, not values',
          instructorNotes: 'Video: 2:17:30'
        }
      ]
    },
    // ── L2-7: Substring & Email Slicer ──────────────────────────────────────
    {
      id: 'le-02-07',
      title: 'Substring & Email Slicer',
      slides: [
        {
          id: 'sl-02-07-01', timestamp: '2:18:57',
          title: 'The substring() Method',
          content: 'substring() extracts a portion of a String using start and end indices.',
          bullets: [
            'str.substring(start) returns everything from index start to the end',
            'str.substring(start, end) returns characters from start up to but NOT including end',
            'Indices are zero-based — first character is at index 0',
            'Pair with indexOf() to extract dynamic portions like the domain of an email'
          ],
          code: 'String text = \"Hello, World!\";\n\nSystem.out.println(text.substring(7));      // World!\nSystem.out.println(text.substring(7, 12));  // World  (ends before !)\nSystem.out.println(text.substring(0, 5));   // Hello\n\n// Dynamic extraction:\nString email    = \"student@example.com\";\nint    atIndex  = email.indexOf(\'@\');\nString username = email.substring(0, atIndex);\nString domain   = email.substring(atIndex + 1);\nSystem.out.println(username);  // student\nSystem.out.println(domain);    // example.com',
          instructorNotes: 'Video: 2:18:57'
        },
        {
          id: 'sl-02-07-02', timestamp: '2:21:00',
          title: 'Email Slicer — Design',
          content: 'The @ character separates username from domain — indexOf() finds it, substring() splits on it.',
          bullets: [
            'indexOf(\'@\') locates the @ symbol position',
            'Username: substring(0, atIndex) — everything before the @',
            'Domain: substring(atIndex + 1) — everything after the @',
            'Validate @ exists first: if indexOf returns -1, the email is malformed'
          ],
          code: 'import java.util.Scanner;\n\npublic class EmailSlicer {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n\n        System.out.print(\"Enter your email: \");\n        String email = sc.nextLine();\n        sc.close();\n\n        int atIndex = email.indexOf(\'@\');\n\n        if (atIndex == -1) {\n            System.out.println(\"Invalid email — missing @\");\n        } else {\n            String username = email.substring(0, atIndex);\n            String domain   = email.substring(atIndex + 1);\n            System.out.println(\"Username: \" + username);\n            System.out.println(\"Domain:   \" + domain);\n        }\n    }\n}',
          instructorNotes: 'Video: 2:21:00'
        },
        {
          id: 'sl-02-07-03', timestamp: '2:24:00',
          title: 'Email Slicer — Challenge',
          content: 'Extend the slicer to also extract the TLD and validate minimum username length.',
          bullets: [
            'lastIndexOf(\'.\') finds the final dot — use it to extract the TLD (.com, .org)',
            'TLD: email.substring(lastDotIndex + 1)',
            'Validate username: if (username.length() < 3) warn the user',
            'Check domain contains at least one dot — indexOf(\'.\') on domain != -1'
          ],
          code: 'String email   = \"dev.alex@university.ac.uk\";\nint atIndex    = email.indexOf(\'@\');\nint lastDot    = email.lastIndexOf(\'.\');\n\nString username = email.substring(0, atIndex);\nString domain   = email.substring(atIndex + 1);\nString tld      = email.substring(lastDot + 1);\n\nSystem.out.printf(\"Username : %s%n\",  username);\nSystem.out.printf(\"Domain   : %s%n\",  domain);\nSystem.out.printf(\"TLD      : .%s%n\", tld);\n\nif (username.length() < 3) {\n    System.out.println(\"Warning: username is very short.\");\n}',
          instructorNotes: 'Video: 2:24:00'
        }
      ]
    }
  ]
};

// ─── CHAPTER 3 ─────────────────────────────────────────────────────────────
const ch03 = {
  id: 'ch-03',
  title: 'Part 3: Control Flow & Loops',
  description: 'Ternary operator, enhanced switch statements, logical operators, and your first loops.',
  lessons: [
    // ── L3-1: Weight Conversion ─────────────────────────────────────────────
    {
      id: 'le-03-01',
      title: 'Weight Conversion Program',
      slides: [
        {
          id: 'sl-03-01-01', timestamp: '2:27:07',
          title: 'Pseudocode First',
          content: 'Write the program plan as comments before any code — pseudocode makes complex programs manageable.',
          bullets: [
            'Pseudocode: write your program steps as plain-English comments before touching Java syntax',
            'Steps: 1) declare variables  2) welcome message  3) prompt for choice  4) convert  5) display',
            'Two options: 1 = pounds to kg,  2 = kg to pounds — anything else is invalid',
            'This project uses: Scanner, double, int, if/else, and arithmetic'
          ],
          code: 'import java.util.Scanner;\n\npublic class WeightConverter {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n\n        // 1. Declare variables\n        double weight, newWeight;\n        int choice;\n\n        // 2. Welcome message\n        System.out.println(\"--- Weight Converter ---\");\n        System.out.println(\"1. Pounds  -> Kilograms\");\n        System.out.println(\"2. Kilograms -> Pounds\");\n\n        // 3. Get choice\n        System.out.print(\"Choose (1 or 2): \");\n        choice = sc.nextInt();\n\n        // 4. Convert and 5. display — next slide\n        sc.close();\n    }\n}',
          instructorNotes: 'Video: 2:27:07'
        },
        {
          id: 'sl-03-01-02', timestamp: '2:29:00',
          title: 'Conversion Formulas',
          content: 'Pounds to kg divides by 2.205; kg to pounds multiplies by 2.205.',
          bullets: [
            '1 pound = 0.453592 kg — equivalently: kg = lbs / 2.205',
            '1 kg = 2.20462 lbs — equivalently: lbs = kg * 2.205',
            'Store the factor as a constant: final double FACTOR = 2.205;',
            'printf with %.2f is standard for weight — two decimal places'
          ],
          code: 'final double FACTOR = 2.205;\n\nSystem.out.print(\"Enter weight: \");\nweight = sc.nextDouble();\n\nif (choice == 1) {\n    newWeight = weight / FACTOR;\n    System.out.printf(\"%.2f lbs = %.2f kg%n\", weight, newWeight);\n\n} else if (choice == 2) {\n    newWeight = weight * FACTOR;\n    System.out.printf(\"%.2f kg = %.2f lbs%n\", weight, newWeight);\n\n} else {\n    System.out.println(\"Not a valid choice.\");\n}',
          instructorNotes: 'Video: 2:29:00'
        },
        {
          id: 'sl-03-01-03', timestamp: '2:32:00',
          title: 'Full Weight Converter',
          content: 'The complete weight converter — all pieces assembled.',
          bullets: [
            'Prompt for choice first, then prompt for the weight value — ordering matters for UX',
            'nextInt() for choice, then nextDouble() for weight — no buffer flush needed between them',
            'printf formats both the input and converted values on the same output line',
            'Challenge: add option 3 for stone to kg (1 stone = 6.35 kg)'
          ],
          code: 'import java.util.Scanner;\n\npublic class WeightConverter {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        final double FACTOR = 2.205;\n\n        System.out.println(\"1. lbs -> kg  |  2. kg -> lbs\");\n        System.out.print(\"Choose: \"); int    choice = sc.nextInt();\n        System.out.print(\"Weight: \"); double weight = sc.nextDouble();\n        sc.close();\n\n        if (choice == 1) {\n            System.out.printf(\"%.2f lbs = %.2f kg%n\",  weight, weight / FACTOR);\n        } else if (choice == 2) {\n            System.out.printf(\"%.2f kg  = %.2f lbs%n\", weight, weight * FACTOR);\n        } else {\n            System.out.println(\"Invalid choice.\");\n        }\n    }\n}',
          instructorNotes: 'Video: 2:32:00'
        }
      ]
    },
    // ── L3-2: Ternary Operator ──────────────────────────────────────────────
    {
      id: 'le-03-02',
      title: 'Ternary Operator',
      slides: [
        {
          id: 'sl-03-02-01', timestamp: '2:35:27',
          title: 'Ternary Syntax',
          content: 'The ternary operator is a compact one-line if/else that resolves to a value.',
          bullets: [
            'Syntax: condition ? valueIfTrue : valueIfFalse',
            'The result can be assigned to a variable or passed directly into println/printf',
            'Read it as: condition is true? use A, otherwise use B',
            'Ternary is NOT a general replacement for if/else — it only resolves to a single expression'
          ],
          code: 'int age = 20;\n\n// Standard if/else:\nString status;\nif (age >= 18) { status = \"adult\"; }\nelse            { status = \"minor\"; }\n\n// Identical with ternary — one line:\nString status2 = (age >= 18) ? \"adult\" : \"minor\";\n\nSystem.out.println(status);   // adult\nSystem.out.println(status2);  // adult',
          instructorNotes: 'Video: 2:35:27'
        },
        {
          id: 'sl-03-02-02', timestamp: '2:37:00',
          title: 'When to Use Ternary',
          content: 'Ternary shines for simple label or value selection — avoid nesting ternaries inside ternaries.',
          bullets: [
            'Great for: labelling (odd/even, pass/fail, yes/no, online/offline)',
            'Great for: picking one of two simple values based on a single condition',
            'Avoid: nested ternaries — they are nearly impossible to read and debug',
            'Avoid: ternaries with side effects — ternary is for selecting a value, not running logic'
          ],
          code: 'int number      = 7;\nboolean passed  = true;\ndouble price    = 49.99;\nboolean isPremium = false;\n\n// Odd/even\nString parity = (number % 2 == 0) ? \"even\" : \"odd\";\nSystem.out.println(number + \" is \" + parity);  // 7 is odd\n\n// Pass/fail\nSystem.out.println(passed ? \"Pass\" : \"Fail\");   // Pass\n\n// Discount\ndouble finalPrice = isPremium ? price * 0.80 : price;\nSystem.out.printf(\"Final: $%.2f%n\", finalPrice);  // $49.99',
          instructorNotes: 'Video: 2:37:00'
        },
        {
          id: 'sl-03-02-03', timestamp: '2:39:00',
          title: 'Ternary Inside println and printf',
          content: 'Embed ternary directly inside print statements for compact conditional output.',
          bullets: [
            'You can nest a ternary expression as an argument to println or printf',
            'This is common in logging and diagnostic output where labels depend on state',
            'Keep the condition simple — if it needs explaining, use if/else instead',
            'Ternary resolves to one value — it cannot replace multi-statement if/else blocks'
          ],
          code: 'int temp        = 25;\nboolean raining = false;\n\n// Ternary directly inside println:\nSystem.out.println(\"Weather: \" + (temp > 30 ? \"hot\" : \"comfortable\"));\n// Weather: comfortable\n\nSystem.out.println(\"Rain: \" + (raining ? \"bring an umbrella\" : \"no rain today\"));\n// Rain: no rain today\n\n// Inside printf:\nSystem.out.printf(\"Temp %dC is %s.%n\", temp, temp >= 20 ? \"warm\" : \"cold\");\n// Temp 25C is warm.',
          instructorNotes: 'Video: 2:39:00'
        }
      ]
    },
    // ── L3-3: Temperature Conversion ────────────────────────────────────────
    {
      id: 'le-03-03',
      title: 'Temperature Conversion Program',
      slides: [
        {
          id: 'sl-03-03-01', timestamp: '2:41:17',
          title: 'Project: Temperature Converter',
          content: 'Build a two-direction temperature converter — C to F or F to C.',
          bullets: [
            'Two directions: Celsius to Fahrenheit, and Fahrenheit to Celsius',
            'Accept the unit as a String input — use toUpperCase() so C or c both work',
            'Use if/else to branch to the correct formula',
            'This project combines: Scanner, String methods, double, if/else, and printf'
          ],
          code: 'import java.util.Scanner;\n\npublic class TempConverter {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n\n        System.out.print(\"Temperature: \");\n        double temp = sc.nextDouble();\n        sc.nextLine(); // flush\n\n        System.out.print(\"Unit (C or F): \");\n        String unit = sc.nextLine().toUpperCase();\n        sc.close();\n\n        // Conversion formulas on next slide\n    }\n}',
          instructorNotes: 'Video: 2:41:17'
        },
        {
          id: 'sl-03-03-02', timestamp: '2:44:00',
          title: 'Celsius and Fahrenheit Formulas',
          content: 'Two formulas, one for each direction — use 9.0/5.0 not 9/5 to avoid integer division.',
          bullets: [
            'Celsius to Fahrenheit: F = C * (9.0 / 5.0) + 32',
            'Fahrenheit to Celsius: C = (F - 32) * (5.0 / 9.0)',
            'Use 9.0 and 5.0 not 9 and 5 — integer division 9/5 = 1, not 1.8',
            'printf with %.1f shows one decimal place — standard for temperature display'
          ],
          code: 'if (unit.equals(\"C\")) {\n    double converted = temp * (9.0 / 5.0) + 32;\n    System.out.printf(\"%.1f C = %.1f F%n\", temp, converted);\n    // 100.0 C = 212.0 F\n\n} else if (unit.equals(\"F\")) {\n    double converted = (temp - 32) * (5.0 / 9.0);\n    System.out.printf(\"%.1f F = %.1f C%n\", temp, converted);\n    // 32.0 F = 0.0 C\n\n} else {\n    System.out.println(\"Enter C or F.\");\n}',
          instructorNotes: 'Video: 2:44:00'
        },
        {
          id: 'sl-03-03-03', timestamp: '2:47:00',
          title: 'Temperature Converter — Challenge',
          content: 'Extend the converter to support Kelvin as a third unit.',
          bullets: [
            'Kelvin to Celsius: C = K - 273.15',
            'Celsius to Kelvin: K = C + 273.15',
            'Add a third else-if branch: else if (unit.equals(\"K\"))',
            'Kelvin has no negatives — validate: if (temp < 0 && unit.equals(\"K\")) print an error'
          ],
          code: '// Challenge: add Kelvin support\nif (unit.equals(\"C\")) {\n    System.out.printf(\"%.2f C = %.2f F%n\", temp, temp * 9.0/5.0 + 32);\n    System.out.printf(\"%.2f C = %.2f K%n\", temp, temp + 273.15);\n\n} else if (unit.equals(\"F\")) {\n    double c = (temp - 32) * 5.0 / 9.0;\n    System.out.printf(\"%.2f F = %.2f C%n\", temp, c);\n    System.out.printf(\"%.2f F = %.2f K%n\", temp, c + 273.15);\n\n} else if (unit.equals(\"K\")) {\n    if (temp < 0)\n        System.out.println(\"Kelvin cannot be negative.\");\n    else\n        System.out.printf(\"%.2f K = %.2f C%n\", temp, temp - 273.15);\n}',
          instructorNotes: 'Video: 2:47:00'
        }
      ]
    },
    // ── L3-4: Enhanced Switch ───────────────────────────────────────────────
    {
      id: 'le-03-04',
      title: 'Enhanced Switch Statements',
      slides: [
        {
          id: 'sl-03-04-01', timestamp: '2:49:12',
          title: 'What is a Switch?',
          content: 'A switch statement is a cleaner alternative to long else-if chains when comparing one variable against many fixed values.',
          bullets: [
            'switch examines one variable and jumps to the matching case — cleaner than 10+ else-if blocks',
            'Java 14 introduced enhanced switch — preferred over classic switch',
            'Classic switch uses colon + break — forgetting break causes fall-through to the next case',
            'Strings, ints, chars, and enums all work as the switch subject'
          ],
          code: 'String day = \"Monday\";\n\n// Long else-if — gets messy quickly\nif      (day.equals(\"Monday\"))   System.out.println(\"Start of week\");\nelse if (day.equals(\"Friday\"))   System.out.println(\"End of week\");\nelse if (day.equals(\"Saturday\")) System.out.println(\"Weekend!\");\nelse if (day.equals(\"Sunday\"))   System.out.println(\"Weekend!\");\nelse                             System.out.println(\"Midweek\");\n\n// Switch is the right tool here -- see next slide',
          instructorNotes: 'Video: 2:49:12'
        },
        {
          id: 'sl-03-04-02', timestamp: '2:51:00',
          title: 'Enhanced Switch Syntax (Java 14+)',
          content: 'Enhanced switch uses -> arrows — no fall-through, no break needed.',
          bullets: [
            'Enhanced switch: case \"x\" -> doSomething(); — stops automatically after each case',
            'Multiple values share one case: case \"Sat\", \"Sun\" -> System.out.println(\"Weekend!\");',
            'The default case handles anything not matched by a named case',
            'Enhanced switch can also be an expression — assign its result to a variable'
          ],
          code: 'String day = \"Saturday\";\n\nswitch (day) {\n    case \"Monday\"             -> System.out.println(\"Start of week\");\n    case \"Friday\"             -> System.out.println(\"TGIF!\");\n    case \"Saturday\", \"Sunday\" -> System.out.println(\"Weekend!\");  // two values\n    default                   -> System.out.println(\"Midweek\");\n}\n// Output: Weekend!\n\n// Switch expression — assign result to variable:\nString type = switch (day) {\n    case \"Saturday\", \"Sunday\" -> \"Weekend\";\n    default                   -> \"Weekday\";\n};\nSystem.out.println(day + \" is a \" + type);',
          instructorNotes: 'Video: 2:51:00'
        },
        {
          id: 'sl-03-04-03', timestamp: '2:54:00',
          title: 'Multi-line Switch Cases with yield',
          content: 'When a case needs multiple statements, wrap them in braces and use yield to return a value.',
          bullets: [
            'Single-statement case: case \"x\" -> value;',
            'Multi-statement case: case \"x\" -> { doA(); doB(); yield value; }',
            'yield is used inside switch expression blocks to return the value for that case',
            'Keep cases short — extract complex logic into a method and call it from the case'
          ],
          code: 'int month = 2;\nint year  = 2024;\n\nint days = switch (month) {\n    case 1, 3, 5, 7, 8, 10, 12 -> 31;\n    case 4, 6, 9, 11           -> 30;\n    case 2 -> {\n        // Multi-statement block — use yield to return\n        boolean isLeap = (year % 400 == 0) ||\n                         (year % 4 == 0 && year % 100 != 0);\n        yield isLeap ? 29 : 28;\n    }\n    default -> -1;\n};\n\nSystem.out.println(\"Days in Feb \" + year + \": \" + days);  // 29',
          instructorNotes: 'Video: 2:54:00'
        },
        {
          id: 'sl-03-04-04', timestamp: '2:56:00',
          title: 'switch vs else-if — When to Choose',
          content: 'Switch is preferred for 3+ fixed values against one variable — else-if for complex boolean conditions.',
          bullets: [
            'Use switch when comparing one variable against 3+ known constant values',
            'Use else-if when conditions involve ranges, multiple variables, or complex logic',
            'switch (score) cannot do >= 90 — ranges require else-if or nesting',
            'Enhanced switch is also more efficient — the JVM can compile it to a jump table'
          ],
          code: '// Switch: one variable, multiple exact values -- clean\nString role = \"admin\";\nswitch (role) {\n    case \"admin\"     -> System.out.println(\"Full access\");\n    case \"editor\"    -> System.out.println(\"Edit access\");\n    case \"viewer\"    -> System.out.println(\"Read-only\");\n    default          -> System.out.println(\"Unknown role\");\n}\n\n// else-if: range comparison -- cannot use switch for this\nint score = 78;\nif      (score >= 90) System.out.println(\"A\");\nelse if (score >= 80) System.out.println(\"B\");\nelse if (score >= 70) System.out.println(\"C\");\nelse                  System.out.println(\"F\");',
          instructorNotes: 'Video: 2:56:00'
        }
      ]
    },
    // ── L3-5: Calculator ────────────────────────────────────────────────────
    {
      id: 'le-03-05',
      title: 'Calculator Project',
      slides: [
        {
          id: 'sl-03-05-01', timestamp: '2:57:44',
          title: 'Project: Calculator with Enhanced Switch',
          content: 'Build a four-operation calculator — enhanced switch selects the operation.',
          bullets: [
            'Accept two numbers and an operator (+, -, *, /) from the user',
            'Use enhanced switch on the operator String to route to the correct calculation',
            'Guard against division by zero: print an error if the divisor is 0',
            'Display the result with printf using %.2f for decimal formatting'
          ],
          code: 'import java.util.Scanner;\n\npublic class Calculator {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n\n        System.out.print(\"First number:      \"); double a  = sc.nextDouble();\n        System.out.print(\"Operator (+,-,*,/): \"); String op = sc.next();\n        System.out.print(\"Second number:     \"); double b  = sc.nextDouble();\n        sc.close();\n\n        // Switch on operator -- next slide\n    }\n}',
          instructorNotes: 'Video: 2:57:44'
        },
        {
          id: 'sl-03-05-02', timestamp: '3:01:00',
          title: 'Switch on the Operator',
          content: 'Route to the correct arithmetic operation using an enhanced switch on the operator string.',
          bullets: [
            'Switch on the operator String: case \"+\" ->, case \"-\" ->, case \"*\" ->, case \"/\" ->',
            'Division needs a zero guard: check b != 0 before dividing',
            'The default case catches any unrecognised symbol and flags it as unknown',
            'Track a valid flag to decide whether to print the result'
          ],
          code: 'double result = 0;\nboolean valid = true;\n\nswitch (op) {\n    case \"+\" -> result = a + b;\n    case \"-\" -> result = a - b;\n    case \"*\" -> result = a * b;\n    case \"/\" -> {\n        if (b == 0) {\n            System.out.println(\"Error: cannot divide by zero.\");\n            valid = false;\n        } else { result = a / b; }\n    }\n    default -> { System.out.println(\"Unknown operator: \" + op); valid = false; }\n}\n\nif (valid) {\n    System.out.printf(\"%.2f %s %.2f = %.2f%n\", a, op, b, result);\n}',
          instructorNotes: 'Video: 3:01:00'
        },
        {
          id: 'sl-03-05-03', timestamp: '3:07:00',
          title: 'Calculator — Challenge',
          content: 'Add modulus and power operators, then wrap the whole program in a loop.',
          bullets: [
            'Add case \"%\" -> result = a % b; for remainder',
            'Add case \"^\" -> result = Math.pow(a, b); for exponentiation',
            'Wrap the input and switch in a while(true) loop — add a quit option (q)',
            'Break out with break when the user types q — this is the standard REPL pattern'
          ],
          code: '// Extended switch — add modulus and power\nswitch (op) {\n    case \"+\" -> result = a + b;\n    case \"-\" -> result = a - b;\n    case \"*\" -> result = a * b;\n    case \"/\" -> {\n        if (b == 0) { System.out.println(\"Div by zero!\"); valid = false; result = 0; }\n        else result = a / b;\n    }\n    case \"%\" -> result = a % b;\n    case \"^\" -> result = Math.pow(a, b);\n    default  -> { System.out.println(\"Unknown operator.\"); valid = false; result = 0; }\n}\n\n// Challenge: wrap the whole program in while(true) { ... }',
          instructorNotes: 'Video: 3:07:00'
        }
      ]
    },
    // ── L3-6: Logical Operators ─────────────────────────────────────────────
    {
      id: 'le-03-06',
      title: 'Logical Operators',
      slides: [
        {
          id: 'sl-03-06-01', timestamp: '3:10:00',
          title: '&& — The AND Operator',
          content: '&& combines two conditions — the result is true only when BOTH sides are true.',
          bullets: [
            'condition1 && condition2 is true only when both conditions are true simultaneously',
            'Short-circuit: if condition1 is false, Java skips condition2 entirely',
            'Use && to enforce multiple requirements: logged in AND is an admin',
            'Truth table: T&&T=T, T&&F=F, F&&T=F, F&&F=F'
          ],
          code: 'int temp        = 22;\nboolean isSunny = true;\n\n// Both must be true\nif (temp >= 18 && isSunny) {\n    System.out.println(\"Good day for a walk!\");  // runs\n}\n\n// Range check — both bounds required\nint score = 75;\nif (score >= 60 && score <= 100) {\n    System.out.println(\"Valid passing score.\");   // runs\n}\n\n// Short-circuit: temp < 30, so isSunny never evaluated\nif (temp >= 30 && isSunny) {\n    System.out.println(\"Hot and sunny.\");         // skipped\n}',
          instructorNotes: 'Video: 3:10:00'
        },
        {
          id: 'sl-03-06-02', timestamp: '3:16:00',
          title: '|| and ! — OR and NOT',
          content: '|| is true when at least one side is true; ! inverts any boolean value.',
          bullets: [
            'condition1 || condition2 is true if EITHER or BOTH conditions are true',
            'Short-circuit: if condition1 is true, Java skips condition2',
            '! inverts a boolean: !true = false, !false = true',
            'Combine && and || with parentheses to control evaluation order'
          ],
          code: 'boolean isWeekend = true;\nboolean isHoliday = false;\n\n// OR — true if either is true\nif (isWeekend || isHoliday) {\n    System.out.println(\"Day off!\");  // runs — isWeekend is true\n}\n\n// NOT — invert a boolean\nboolean isWorking = !isWeekend;\nSystem.out.println(\"Working: \" + isWorking);  // Working: false\n\n// Combined\nint age = 17;\nboolean hasPermission = false;\nif (age >= 18 || hasPermission) {\n    System.out.println(\"Granted.\");\n} else {\n    System.out.println(\"Denied.\");  // runs\n}',
          instructorNotes: 'Video: 3:16:00'
        },
        {
          id: 'sl-03-06-03', timestamp: '3:22:00',
          title: 'Combining Operators — Precedence',
          content: '&& binds tighter than || — always use parentheses when mixing them.',
          bullets: [
            '&& has higher precedence than || — a || b && c means a || (b && c)',
            'Always add parentheses when mixing && and || to make intent unambiguous',
            'Chaining: (a && b && c) all three must be true; (a || b || c) at least one',
            'De Morgan\'s law: !(a && b) equals (!a || !b) — useful for simplifying negated conditions'
          ],
          code: 'int age         = 25;\nboolean isEmployee = true;\nboolean hasBadge   = false;\n\n// Precedence trap: && binds tighter\n// Reads as: age>=18 || (isEmployee && hasBadge)\nif (age >= 18 || isEmployee && hasBadge) {\n    System.out.println(\"Enters — age>=18 is true\");  // runs\n}\n\n// Explicit parentheses — different result\nif ((age >= 18 || isEmployee) && hasBadge) {\n    System.out.println(\"Secure area\");  // skipped — hasBadge is false\n}',
          instructorNotes: 'Video: 3:22:00'
        }
      ]
    },
    // ── L3-7: While Loops ───────────────────────────────────────────────────
    {
      id: 'le-03-07',
      title: 'While Loops',
      slides: [
        {
          id: 'sl-03-07-01', timestamp: '3:25:00',
          title: 'The while Loop',
          content: 'A while loop repeats a block of code as long as its condition remains true.',
          bullets: [
            'Syntax: while (condition) { // repeated code }',
            'Condition is checked BEFORE each iteration — if false from the start, body never runs',
            'You must update something inside the loop that eventually makes the condition false',
            'while loops are ideal when you do not know in advance how many times to repeat'
          ],
          code: 'int i = 1;\n\nwhile (i <= 5) {\n    System.out.println(\"Count: \" + i);\n    i++; // update — without this the loop runs forever\n}\n// Count: 1\n// Count: 2\n// Count: 3\n// Count: 4\n// Count: 5\n\nSystem.out.println(\"Loop ended. i = \" + i);  // i = 6',
          instructorNotes: 'Video: 3:25:00'
        },
        {
          id: 'sl-03-07-02', timestamp: '3:27:00',
          title: 'Infinite Loops — Avoiding Them',
          content: 'A loop whose condition never becomes false runs forever and freezes your program.',
          bullets: [
            'Infinite loop: the condition is never updated to false inside the body',
            'Common causes: forgetting i++, wrong condition direction, or an unreachable exit',
            'Intentional loop: while (true) { ... } — must exit with break or return',
            'If the program freezes: hit the red Stop button in IntelliJ or press Ctrl+C in the terminal'
          ],
          code: '// INFINITE LOOP — do NOT run as-is:\n// int x = 0;\n// while (x < 5) {\n//     System.out.println(x);\n//     // x is never incremented -- runs forever\n// }\n\n// Intentional loop with a break exit:\nint attempts = 0;\nwhile (true) {\n    attempts++;\n    System.out.println(\"Attempt \" + attempts);\n    if (attempts >= 3) {\n        break; // exit the loop\n    }\n}\nSystem.out.println(\"Done after \" + attempts + \" attempts.\");',
          instructorNotes: 'Video: 3:27:00'
        },
        {
          id: 'sl-03-07-03', timestamp: '3:29:00',
          title: 'do-while Loop',
          content: 'do-while runs the body at least once, then checks the condition.',
          bullets: [
            'Syntax: do { // code } while (condition);  — note the semicolon after the closing parenthesis',
            'Body executes FIRST, condition checked AFTER — guaranteed at least one iteration',
            'Use do-while when the first run must always happen regardless of the condition',
            'Classic use: menu loops — show the menu at least once, repeat until the user quits'
          ],
          code: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int choice;\n\n        // do-while — shows the menu at least once\n        do {\n            System.out.println(\"1. Play  |  2. Quit\");\n            System.out.print(\"Choice: \");\n            choice = sc.nextInt();\n        } while (choice != 2);\n\n        System.out.println(\"Goodbye!\");\n        sc.close();\n    }\n}',
          instructorNotes: 'Video: 3:29:00'
        },
        {
          id: 'sl-03-07-04', timestamp: '3:31:00',
          title: 'Practice: Input Validation Loop',
          content: 'Use a while loop to keep prompting the user until they enter a valid value.',
          bullets: [
            'Initialise the variable to an invalid value so the loop starts: int age = -1;',
            'Loop condition: while the value is outside the valid range, keep asking',
            'Print an error message inside the loop to guide the user',
            'Input validation is essential for any real program — never assume the user enters correct data'
          ],
          code: 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int age = -1;\n\n        while (age < 0 || age > 120) {\n            System.out.print(\"Enter your age (0-120): \");\n            age = sc.nextInt();\n\n            if (age < 0 || age > 120) {\n                System.out.println(\"Invalid. Try again.\");\n            }\n        }\n\n        System.out.println(\"Valid age: \" + age);\n        sc.close();\n    }\n}',
          instructorNotes: 'Video: 3:31:00'
        }
      ]
    }
  ]
};

cur.chapters.push(ch02);
cur.chapters.push(ch03);

fs.writeFileSync(
  path.join(__dirname, '../src/data/curriculum.json'),
  JSON.stringify(cur, null, 2)
);

console.log('Done.');
cur.chapters.forEach(ch => {
  const slides = ch.lessons.reduce((s, l) => s + l.slides.length, 0);
  console.log(`  ${ch.title} — ${ch.lessons.length} lessons, ${slides} slides`);
});
